cms/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from cms import views


urlpatterns = patterns('',

    url(r'^$', views.Search_view, name='search_result'),   # 検索用
    #url(r'^search/$', views.Search_all, name='search_all'),   # 全件出力　不要機能
    url(r'^search/detail/(?P<item_id>\d+)/$', views.Item_detail_view, name='item_detail'),  # 項目の詳細
)

itoen/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'itoen.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'itoen.views.home', name='home'),  #トップページ
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cms/', include('cms.urls', namespace='cms')),   # 検索結果用
)

cms/models.py
# -*- coding: utf-8 -*-
from django.db import models

#クラスの項目名は頭が小文字、テーブル名は大文字、単数と複数を意識したネーミングを
#related_nameは多い方を複数形にする


###   マスタ系     ######
class ItemCatogory(models.Model):
    '''項目のカテゴリ'''
    categoryName = models.CharField(u'項目カテゴリ', max_length=255,primary_key=True)

    class Meta:
        verbose_name = verbose_name_plural = u"1.項目カテゴリ(声優とか食べ物とか)"


    def __unicode__(self):    # Python2: def __unicode__(self):
        return self.categoryName


class QuoteCategory(models.Model):
    '''引用元マスタ'''
    quoteCategory = models.CharField(u'引用元カテゴリ', max_length=255,primary_key=True)   
    Category_Choices = (
    	(u'0',u'ブログ'),
    	(u'1',u'書籍'),
    	(u'2',u'ラジオ'),
    	(u'3',u'イベント'),
       	(u'4',u'その他'),
    	)
    category = models.CharField(max_length=1, choices=Category_Choices,default='0')

    class Meta:
        verbose_name = verbose_name_plural = u"2.引用元カテゴリ(ブログとか)"


    def __unicode__(self):    # Python2: def __unicode__(self):
        return self.quoteCategory

### 1:N  quote：fact
class Quote(models.Model):
    '''引用'''
    quoteName = models.CharField(u'引用元', max_length=255)
    quoteCategory = models.ForeignKey(QuoteCategory, verbose_name=u'引用元種類', related_name='quotecategory')
    quoteUrl = models.URLField((u'ソースURL'), null=True, blank=True)
    publishDate = models.DateField(u'発表された日付')

    class Meta:
        verbose_name = verbose_name_plural = u"3.引用元(ブログの記事とかラジオタイトルとか)"

    def __unicode__(self):    # Python2: def __unicode__(self):
        return self.quoteName


#fact　N:N　item
class Item(models.Model):
    '''項目'''
    itemName = models.CharField(u'項目名', max_length=255)
    itemNameKana = models.CharField(u'項目名カナ', max_length=255)
    itemCategory = models.ForeignKey(ItemCatogory, verbose_name=u'カテゴリ', related_name='itemcategories')
    itemOutline = models.TextField(u'概要', max_length=255,blank=True)

    class Meta:
        verbose_name = verbose_name_plural = u"5.項目登録"

    def __unicode__(self):    # Python2: def __unicode__(self):
        return self.itemName


class Fact(models.Model):
    '''事実'''
    quote = models.ForeignKey(Quote, verbose_name=u'出展元', related_name='facts')
    info = models.TextField(u'事実')
    aboutDate = models.DateField(u'ソース内で述べられている日付')
    In_date_Choices = (
        (u'0',u'確証有り'),
        (u'1',u'上旬頃'),
        (u'2',u'中旬頃'),
        (u'3',u'下旬頃'),
        (u'4',u'この日付と思われるが確証無し'),
        (u'9',u'日付不明'),
        )
    inDate = models.CharField(u'日付の精度', max_length=1, choices=In_date_Choices,default='0')
    items = models.ManyToManyField(Item)

    class Meta:
        verbose_name = verbose_name_plural = u"4.引用元に対して事実を登録"

    def __unicode__(self):    # Python2: def __unicode__(self):
        return self.info




#class FactTag(models.Model):
#    '''事実とアイテムのタグ'''
#    facttag = models.ForeignKey(Fact, verbose_name=u'事実', related_name='facttags')
#    itemtag = models.ForeignKey(Item, verbose_name=u'項目', related_name='itemtags')

#    def __int__(self):    # Python2: def __unicode__(self):
#        return self.id

cms/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
from cms.models import Item,Fact,Quote,ItemCatogory,QuoteCategory


def Search_all(request):
    #項目名が一致する項目を取得し、その項目から事実を取得、その事実を持つ項目を返す
    items = Item.objects.all().order_by('itemNameKana')
    return render_to_response('cms/search.html',  # 使用するテンプレート
                              {'items': items},       # テンプレートに渡すデータ
                              context_instance=RequestContext(request))  # その他標準のコンテキスト



def Search_view(request):
    '''検索結果の一覧'''
    #項目名が一致する項目を取得し、その項目から事実を取得、その事実を持つ項目を返す

    errors = []
    if request.method == 'GET':

        if 'word' in request.GET:
            word = request.GET['word']
            items = Item.objects.filter(itemName__icontains=word)
            return render_to_response('cms/search.html',  # 使用するテンプレート
                                     {'items': items},     # テンプレートに渡すデータ
                                     context_instance=RequestContext(request))  # その他標準のコンテキスト
        else:
            errors.append('何か入れてよ！')          
            return render_to_response(request, 'itoen/index.html',{'errors': errors})

                          
                              

def Item_detail_view(request, item_id=None,search_rslt=None):
    '''該当する事実を表示'''

    item = get_object_or_404(Item, pk=item_id)

    #多対多の逆参照(子→親)の場合はモデル名を小文字にして後ろに＿setをつける
    #アイテムの項目番号をキーに事実を取得する、この時点でfactとquote等関連するデータすべて持ってきてる
    facts = item.fact_set.all() 
    


    return render_to_response('cms/detail.html',
                              {'item': item,'facts':facts},
                              context_instance=RequestContext(request))

itoen/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
from cms.models import Item,Fact,Quote,ItemCatogory,QuoteCategory



def home(request):
    
    mongon = '伊藤苑'
    
    return render_to_response('itoen/index.html',        # 使用するテンプレート
                              {'mongon': mongon},       # テンプレートに渡すデータ
                              context_instance=RequestContext(request))  # その他標準のコンテキスト

cms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}My books{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>

cms/templates/cms/detail.html
{% extends "base.html" %}

{% block title %}詳細表示{% endblock title %}

{% block extrahead %}

<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}


{% block content %}
    <h3 class="page-header">{{ item.itemName }}</h3>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>関連情報</th>
            <th>出展元</th>
            <th>日付</th>
          </tr>
        </thead>
        <tbody>
          {% for fact in facts %}
          <tr>
            <td>{{fact.info}}</td>
              {% if fact.quote.quoteUrl == '' %}
                 <td>{{fact.quote.quoteName}}</td>
              {% else %}
                 <td><a href="{{fact.quote.quoteUrl}}" target=”_blank”>{{fact.quote.quoteName}} </a></td>
              {% endif %}             
            <td>{{fact.aboutDate}}</td>
          </tr>
          {% endfor %}
       <tbody>
      </table>
    <div>
      <Form><Input class="btn btn-default btn-xs" value="閉じる" onClick="javascript:window.close();"></Form> 
    </div>
{% endblock content %}

cms/templates/cms/search.html
{% extends "base.html" %}

{% block title %}項目一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
<nav class="navbar navbar-default">
  <!--コンテナーフィールド：画面サイズに合わせてナビゲーションバーを変更-->
  <div class="container-fluid">
      <div class="navbar-header">
        <a href="/" class="navbar-brand">伊藤苑</a>
      </div>
      <!--入力フォーム-->
      <!--ナビゲーションバーのフォーム　cmsアプリのsearch_resultメソッドを、getで呼ぶ-->
      <form class="navbar-form" action="{% url 'cms:search_result' %}" method="get">
           <div class="form-group">
               <input type="text" name="word" class="form-control" placeholder="検索ワード">
                <button type="submit" class="btn btn-success">検索</button>
           </div>
      </form>
  </div>
</nav>

<h3 class="page-header">検索結果の一覧</h3>
<div class="container" style="padding:5px 0">
   <table class="table table-striped table-bordered">
      <thead>
           <tr>
               <th class="col-xs-4 col-sm-4 col-md-4"><nobr>項目名</nobr></th>
               <th class="col-xs-7 col-sm-7 col-md-7">概要</th>
               <th class="col-xs-1 col-sm-1 col-md-1">詳細</th>
           </tr>
      </thead>
      <tbody>
           {% for item in items %}
           <tr>
               <td class="col-xs-4 col-sm-4 col-md-4"><nobr>{{ item.itemName }}</nsobr></td>
               <td class="col-xs-7 col-sm-7 col-md-7">{{ item.itemOutline }}</td>
               <td class="col-xs-1 col-sm-1 col-md-1">
                   <Form><input name="openWin" class="btn btn-info" value="詳細" 
                      onClick="window.open('{% url 'cms:item_detail' item_id=item.id %}',
                      '','scrollbars=yes,width=1000,height=500,');">
                   </Form>
              </td> 
           </tr>
           {% endfor %}
      </tbody>
     
    </table>
    </div>    
{% endblock content %}

cms/templates/itoen/index.html
{% extends "base.html" %}

{% block title %}伊藤苑{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}


{% block content %}



<nav class="navbar navbar-default">
  <!--コンテナーで囲う-->
  <div class="container-fluid">
      <div class="navbar-header">
          <p class="navbar-text">伊藤苑</p>
      </div>
      <!--入力フォーム-->
      <!--ナビゲーションバーのフォーム　cmsアプリのsearch_resultメソッドを、getで呼ぶ-->
      <form class="navbar-form" action="{% url 'cms:search_result' %}" method="get">
           <div class="form-group">
               <input type="text" name="word" class="form-control" placeholder="検索ワード">
           </div>
           <button type="submit" class="btn btn-success">検索</button>
      </form>
  </div>
</nav>

 

{% endblock content %}